### PR TITLE
Add note that proposal is not being pursued

### PR DESCRIPTION
**Pull request by jpchase**

### CODE REVIEW

**Comment by jpchase** [comment]
@yoavweiss Would you review? I don't know anyone else with access. I want to make it clear that instrinsicsize is not being pursued anymore.

**Comment by eeeps** [comment]
Was there a public discussion about this somewhere?

Is Chrome planning to support Mozilla’s `width`/`height`-reusing proposal, instead? (#16)

**Comment by jpchase** [comment]
The main reason to add this note is to point to #16 (specifically [this comment](https://github.com/WICG/intrinsicsize-attribute/issues/16#issuecomment-503245998)), to make it clear that's where efforts are focused now, rather than the intrinsicsize proposal. Chrome is planning to support that proposal (also see [this comment](https://github.com/WICG/intrinsicsize-attribute/issues/16#issuecomment-506913077) for the Chromium bug to track the work).

Chrome folks started the intrinsicsize proposal, and we aren't aware of any other folks working on it, so it seems appropriate to set expectations. 

Do you think it would be helpful to add more explanatory text? My thinking was that #16 would provide enough context.

**Comment by eeeps** [comment]
Yeah, adding a note to the top of the README would be helpful (ala https://github.com/WICG/user-gesture-nav or https://github.com/WICG/aspect-ratio).

And I suppose after the open threads from #16 (and other issues?) have been captured in issues on HTML (and[ CSS-Sizing](https://drafts.csswg.org/css-sizing-3/)?), archive this repo.

**Review by yoavweiss — APPROVED** [review]
LGTM

**Pull request merged**
